# Generated by Django 5.1 on 2024-09-11 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название породы')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs.breed')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(verbose_name='Имя')),
                ('last_name', models.TextField(verbose_name='Фамилия')),
                ('phone_number', models.TextField(verbose_name='Номер телефона')),
                ('dogs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs.dog')),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название прививки')),
                ('date', models.DateField(verbose_name='Дата прививки')),
                ('dogs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs.dog')),
            ],
            options={
                'verbose_name': 'Прививка',
                'verbose_name_plural': 'Прививки',
            },
        ),
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('weight', models.TextField(verbose_name='Вес (кг)')),
                ('dogs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs.dog')),
            ],
            options={
                'verbose_name': 'Запись веса',
                'verbose_name_plural': 'Записи веса',
            },
        ),
    ]
