# Generated by Django 5.1 on 2024-09-15 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_remove_owner_dogs_dog_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='dogs',
        ),
        migrations.RemoveField(
            model_name='weightentry',
            name='dogs',
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='dogs.vaccination'),
        ),
        migrations.AddField(
            model_name='dog',
            name='weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='dogs.weightentry'),
        ),
    ]
