# Generated by Django 5.1 on 2024-09-15 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_remove_vaccination_dogs_remove_weightentry_dogs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='vaccination',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='weight',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='dogs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dog_vaccinations', to='dogs.dog'),
        ),
        migrations.AddField(
            model_name='weightentry',
            name='dogs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dog_weights', to='dogs.dog'),
        ),
    ]
