# Generated by Django 5.1 on 2024-09-15 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_remove_dog_vaccination_remove_dog_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(verbose_name='Страна проживания')),
            ],
            options={
                'verbose_name': 'Страна проживания',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hobby', models.TextField(verbose_name='Название хобби')),
            ],
            options={
                'verbose_name': 'Хобба',
                'verbose_name_plural': 'Хобби',
            },
        ),
        migrations.RemoveField(
            model_name='weightentry',
            name='dogs',
        ),
        migrations.AddField(
            model_name='dog',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dog_country', to='dogs.country'),
        ),
        migrations.AddField(
            model_name='dog',
            name='hobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dog_hobby', to='dogs.hobby'),
        ),
        migrations.DeleteModel(
            name='Vaccination',
        ),
        migrations.DeleteModel(
            name='WeightEntry',
        ),
    ]
