# Generated by Django 5.1 on 2024-10-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0005_country_hobby_remove_weightentry_dogs_dog_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="picture",
            field=models.ImageField(
                null=True, upload_to="dogs", verbose_name="Изображение"
            ),
        ),
    ]
