# Generated by Django 5.1 on 2024-10-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0006_dog_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="pictureOwner",
            field=models.ImageField(
                null=True, upload_to="owner", verbose_name="Изображение"
            ),
        ),
    ]
