# Generated by Django 5.1 on 2024-11-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0011_dog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="pictureOwner",
            field=models.ImageField(
                blank=True, null=True, upload_to="owner", verbose_name="Изображение"
            ),
        ),
    ]
